// Generated by CoffeeScript 1.7.1
(function() {
  var key, val, _ref;

  _ref = require('./aurora');
  for (key in _ref) {
    val = _ref[key];
    exports[key] = val;
  }

  require('./devices/node-speaker');

}).call(this);
